#!/bin/bash
cut -c 1 | paste -s -d"#!/bin/bash
cut -c 1 | paste -s -d"#!/bin/bash
cut -c 1 | paste -s -d"#!/bin/bash
cut -c 1 | paste -s -d"#!/bin/bash
cut -c 1 | paste -s -d"#!/bin/bash
cut -c 1 | paste -s -d"#!/bin/bash
cut -c 1 | paste -s -d"#!/bin/bash
cut -c 1 | paste -s -d"#!/bin/bash
cut -c 1 | paste -s -d"
